# Generated by Django 3.2.2 on 2021-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "male"), ("FEMALE", "female")], max_length=6
                    ),
                ),
                ("company", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=150)),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=7, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
            ],
        ),
    ]
